# Generated by Django 4.2.5 on 2023-12-13 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('article_text', models.TextField()),
                ('theme', models.CharField(choices=[('theme1', 'Политика'), ('theme2', 'Регионы')], default='', max_length=50)),
            ],
        ),
    ]
