# Generated by Django 4.2.5 on 2023-12-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_image_alter_news_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='isNewsOfDay',
            field=models.BooleanField(default=False),
        ),
    ]
