# Generated by Django 5.0.1 on 2024-01-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_isnewsofday'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='article_text_en',
            field=models.TextField(default=''),
        ),
    ]
