# Generated by Django 5.0.1 on 2024-01-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_article_text_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.TextField(default='', max_length=200),
        ),
    ]
